Require gem/release/version in GitHub Context
Otherwise we'll have:

ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Release::VERSION
Did you mean?  Gem::Release::Version
               Gem::Version
               Gem::VERSION