Setup Net::HTTP client to use ssl when needed
GitHub API URLs protocol is https so we have to explicitely
set the client to use this option, otherwise we would have an
error:

ERROR:  While executing gem ... (EOFError)
    end of file reached

See also https://stackoverflow.com/a/9227933/1460504